MCMD.Web/Controllers/Administration/SpecialityController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MCMD.EntityModel.Doctor;
using MCMD.IRepository.AdminInterfaces;
using MCMD.EntityRepository.AdminRepository;
using MCMD.ViewModel.Administration;

namespace MCMD.Web.Controllers.Administration
{
    public class SpecialityController : Controller
    {
        public MCMD.EntityModel.ApplicationDbContext db = new MCMD.EntityModel.ApplicationDbContext();

        private ISpecialityRepository specialityRepository;
        public SpecialityController(ISpecialityRepository _specialityRepository)
        {
            this.specialityRepository = _specialityRepository;
        }
        // [HttpGet]
        // GET: Speciality
      

        #region Edit speciality
        public ActionResult UserEditSpeciality(int Id)
        {
            Session["EditSpeciality"] = Id;
            var varid = Id;
            return Json(new { varid }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Create/View Speciality
        public ActionResult Create()
        {
            @TempData["Name"] = Session["Name"];
            SpecialityViewModel _specialityVM = new SpecialityViewModel();
            _specialityVM.SpecialityList = specialityRepository.GetSpecialitys().Where(x => x.InactiveFlag == "N").ToList();

            int editInputs = (Session["EditSpeciality"] != null) ? (Convert.ToInt32(Session["EditSpeciality"])) : 0;

            if (editInputs != 0)
            {
                List<Speciality> _NewSpeciality = specialityRepository.GetSpecialitys().Where(x => x.SpecialityID == editInputs).ToList();

                foreach (var item in _NewSpeciality)
                {
                    _specialityVM.SpecialityName = item.SpecialityName;

                   // Session["EditSpeciality"] = null;
                }

            }

            return View(_specialityVM);

        }
     

        [HttpPost]
        public ActionResult Create(SpecialityViewModel specialityVM)
        {
     //     var cSpeciality = specialityRepository.CheckSpeciality(specialityVM.specialitys.SpecialityName);

            var cSpeciality = db.Specialitys.FirstOrDefault(x => x.SpecialityName == specialityVM.SpecialityName);
            try
            {
                if (ReferenceEquals(cSpeciality, null))
                {
                    if (ModelState.IsValid)
                    {

                        var newSpeciality = new Speciality();
                        if (Session["EditSpeciality"] != null)
                        {
                            newSpeciality.SpecialityID = Convert.ToInt32(Session["EditSpeciality"]);
                            newSpeciality.SpecialityName = specialityVM.SpecialityName;
                            newSpeciality.InactiveFlag = "N";
                            newSpeciality.ModifiedDate = DateTime.Now;
                            specialityRepository.UpdateSpeciality(newSpeciality);
                            Session["EditSpeciality"] = null;
                           

                        }else
                        {
                            specialityRepository.InsertSpeciality(specialityVM, specialityVM.specialityss);
                            
                        }
                        specialityRepository.Save();
                        @TempData["SuccessMessage"] = "Added Successfully....";
                       
                    }
                }
                else
                {
                 //   ModelState.AddModelError("Speciality.SpecialityName", "Speciality Name Already Exist");
                    @TempData["Message"] =""+ specialityVM.SpecialityName+ "Speciality Name Already Exist";

                }
           }
            catch (Exception)
            {
                ModelState.AddModelError(string.Empty, "Unable to Add changes. Try again, and if the problem persists contact your system administrator.");
            }
            return RedirectToAction("Create");
        }

        #endregion


        #region Delete Speciality
        [HttpPost]
        public ActionResult BatchDelete(int[] deleteInputs)
        {

            if (deleteInputs != null)
            {
                foreach (var item in deleteInputs)
                {

                    Speciality specialitys = db.Specialitys.Find(item);
                    if (User == null)
                    {
                        // return HttpNotFound();
                    }
                    else
                    {
                        specialitys.InactiveFlag = "Y";
                        specialitys.ModifiedDate = DateTime.Now;

                        specialityRepository.UpdateSpeciality(specialitys);
                        specialityRepository.Save();
                        @TempData["SuccessMessage"] = "User having speciality " + specialitys.SpecialityName + " is deleted successfully";

                    }
                    
                       
                    
                }

            }
            return Json("User", JsonRequestBehavior.AllowGet);
        }

        #endregion

    }
}

MCMD.Web/Views/Speciality/Create.cshtml
@model MCMD.ViewModel.Administration.SpecialityViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ThemeLayout.cshtml";
}

@{

    int Pages = 20;
    WebGrid grid = new WebGrid(Model.SpecialityList, canPage: true, rowsPerPage: Pages);
    grid.Pager(WebGridPagerModes.NextPrevious);
}
@*<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>*@
<script type="text/javascript">

    //Delete User on click
    function DeleteUserData(varid) {
        if (varid != null) {
            if (confirm('Are you sure want to delete the selected user')) {
                var deleteInputs = [];
                //$('.chkview:checked').each(function (i, chk) {
                deleteInputs.push(varid);
                //});
                var url = '@Url.Action("BatchDelete", "Speciality")';
                $.ajax({
                    type: "POST",
                    async: false,
                    cache: false,
                    url: url,
                    traditional: true,
                    data: { deleteInputs: deleteInputs },
                    success: function (data) {
                        var url = '@Url.Action("Create", "Speciality")';
                        window.location.href = url;

                    }
                });
            }
        }
    }

    function EditUserData(varid) {
        if (varid != null) {
            if (confirm('Are you sure want to edit the details selected user')) {
                var Inputs = [];
                //$('.chkview:checked').each(function (i, chk) {
                Inputs.push(varid);
                //});
                var url = '@Url.Action("UserEditSpeciality", "Speciality")';
                $.ajax({
                    type: "POST",
                    async: false,
                    cache: false,
                    url: url,
                    traditional: true,
                    data: { Id: Inputs },
                    success: function (data) {
                        alert(data)
                        window.location.reload();
                    }
                });
            }
        }
    }

</script>
<div class="container-fluid">
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
        <div class="span12">
           
            <h3 class="page-title"></h3>
            <ul class="breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="">Home</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li>
                    <a href="#">Speciality</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li>
                    <a href="#">Create Speciality</a>
                    <span class="icon-angle-right"></span>
                </li>

            </ul>
        </div>
        <div>
            <span class="text-success">@TempData["SuccessMessage"]</span>
            <span class="text-error">@TempData["Message"]</span>
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="portlet box blue ">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i>Create/Add Speciality</div>

        </div>

        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            @using (Html.BeginForm(Html.BeginForm("Create", "Speciality",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "form-horizontal form-bordered" })))
            {

                @Html.ValidationSummary(true)
                @Html.AntiForgeryToken()
                <div class="control-group">
                    <label class="control-label">Speciality Name</label>
                    <div class="controls">
                        @Html.TextBoxFor(model => model.SpecialityName, new { @class = "m-wrap span6", @placeholder = "Enter Speciality Name", @maxlength = "50", @autocomplete = "off" })
                        @Html.ValidationMessageFor(model => model.SpecialityName, string.Empty, new { @class = "text-error" })

                    </div>
                </div>
                <div class="form-actions">
                    <button type="Submit" id="btnCreate" name="btnCreate" class="btn blue">Submit</button>
                    <button type="button" id="btnReset" class="btn" name="btnscd" onclick="location.href='@Url.Action("Create", "Speciality")'">Reset</button>
                </div>
            }



            <!-- END FORM-->
        </div>


    </div>

    <div class="portlet-title">


        <div class="portlet-body">

            @grid.GetHtml(
                                                    tableStyle: "table table-border table-hover",
                                         footerStyle: "gridFooter",
                                                alternatingRowStyle: "alt",
                                                 htmlAttributes: new { id = "grdUsers" },
                                                 mode: WebGridPagerModes.All,
                                               firstText: "<< First",
                            previousText: "< Previous", nextText: "Next >",
                            lastText: "Last >>",
                                             columns: new[] {
                                             //grid.Column("ID",header: "Speciality ID", canSort: false),
                                             grid.Column("SpecialityName",header: "Speciality Name", canSort: false),
                                              grid.Column(header: "Option", format: @<text>

                                                <a id="btnEdit" style="cursor:pointer;" onclick="EditUserData( @item.SpecialityID)">Edit</a>
                                                @*<a id="btnDelete" style="cursor:pointer;" onclick="DeleteUserData( @item.SpecialityID)">Delete</a>*@
                                            </text>)
                                        })



        </div>
    </div>
    <!-- END PAGE CONTENT-->
</div>



@Scripts.Render("~/bundles/jqueryval")

MCMD.Web/Views/Speciality/Index.cshtml
@model IEnumerable<MCMD.ViewModel.Administration.SpecialityViewModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>