MCMD.Web/Controllers/Administration/UserController.cs
 using System;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MCMD.ViewModel.Administration;
using System.Threading.Tasks;
using System.Data.Entity;
using System.Data.SqlClient;
using MCMD.IRepository.AdminInterfaces;
using MCMD.EntityRepository.AdminRepository;
using MCMD.EntityModel.Administration;
using System.Web.Security;
using System.Data.Entity.Validation;
using MCMD.Web.Controllers.Account;
using MCMD.EntityModel;
using MCMD.Common.CommonClass;

namespace MCMD.Web.Controllers.Administration
{

    public class UserController : Controller
    {

        public ApplicationDbContext db = new ApplicationDbContext();
        private IUserRepository userRepository;
        public UserController(IUserRepository _userRepositorys)
        {
            this.userRepository = _userRepositorys;
        }

                     
        #region Create User
        [HttpGet]
        public ActionResult RegisterUser()
        {
            @TempData["Name"] = Session["Name"];

            UserRegisterViewModel _userRegisterViewModel = new UserRegisterViewModel();
            _userRegisterViewModel.Roles = userRepository.GetRoles().ToList();
            _userRegisterViewModel.Specialitys = userRepository.GetSpecialitys().Where(x => x.InactiveFlag=="N").ToList();
            _userRegisterViewModel.Userlogins = new UserLogin();

            return View(_userRegisterViewModel);

        }

        [HttpPost]
        public ActionResult RegisterUser(UserRegisterViewModel registerVM)
        {

            ModelState.Clear();  // Cleare Model state
            if (ModelState.IsValid)
            {

                //var cUser = db.UserLogins.FirstOrDefault(x => x.UserName == registerVM.Userlogins.UserName);
                var cUserEmail = db.UserLogins.FirstOrDefault(x => x.EmailID == registerVM.Userlogins.EmailID);
                var cEmpId = db.UserLogins.FirstOrDefault(X => X.EmployeeId == registerVM.Userlogins.EmployeeId);

                //if (ReferenceEquals(cUser, null))
                //{
                    if (ReferenceEquals(cUserEmail, null))
                    {
                        if (ReferenceEquals(cEmpId, null))
                        {
                            using (var dbContextTransaction = db.Database.BeginTransaction())
                            {
                                try
                                {

                                    //Take the password for email
                                    string password = registerVM.Userlogins.Password;

                                    //Insert data in Userlogins  Table                             
                                    userRepository.InsertUserLogins(registerVM.Userlogins, registerVM);
                                    userRepository.Save();

                                    //Insert data in Login_Role Table
                                    var newUserRole = db.UserLoginRoles.Create();
                                    userRepository.InsertUserLoginRoles(newUserRole, registerVM);
                                    userRepository.Save();

                                    //  Insert data in Login_Speciality Table
                                    if (registerVM.SpecialityID != 0)
                                    {
                                        var newUserspeciality = db.UserLoginSpecialitys.Create();
                                        userRepository.UserLoginSpecialitys(newUserspeciality, registerVM);
                                        userRepository.Save();

                                    }

                                    dbContextTransaction.Commit();
                                    //ViewBag.StatusMessage = " User Name with " + registerVM.Userlogins.UserName + " having Email Id " + registerVM.Userlogins.EmailID + " is created successfully";
                                    //ViewBag.Status = 1;
                                    @TempData["SuccessMessage"] = " User Name with " + registerVM.Userlogins.FirstName + "&nbsp;" + registerVM.Userlogins.LastName + " having Email Id " + registerVM.Userlogins.EmailID + " is created successfully";

                                    //var callbackUrl = Url.Action("ConfirmEmail", "Account",new { userId = user.Id, code = code },protocol: Request.Url.Scheme);

                                    //get user emailid
                                    var emailid = registerVM.Userlogins.EmailID;
                                    //send mail
                                    string subject = "doxedox  Registration";
                                    string body = "Dear " + registerVM.Userlogins.FirstName + " " + registerVM.Userlogins.LastName + "<br/> <br/>" + System.Environment.NewLine + System.Environment.NewLine + "You have been successfully registered at doxedox , Your login credentials are given below<br/><br/>" 
                                   +"Your Id" + " : " + registerVM.Userlogins.LoginId + "<br/><br/>Password" + " : " +
                                     password + "<br/><br/><br/>Thank You" + "<br/>Admin" + "<br/>doxedox";  //edit it
                                    try
                                    {
                                        SendEMail sendemail = new SendEMail();
                                        sendemail.Send_EMail(emailid, subject, body);
                                        @TempData["SuccessMessage"] = "User has been created Successfully. Email sent to " + registerVM.Userlogins.EmailID + "";
                                    }
                                    catch (Exception ex)
                                    {
                                        // ViewBag.StatusMessage = "User has been created successfully but Error occurred while sending email. Error:" + ex.Message;
                                        @TempData["Message"] = "User has been created successfully but Error occurred while sending email. Error:" + ex.Message;
                                    }
                                }
                                catch (DbEntityValidationException)
                                {

                                    dbContextTransaction.Rollback();

                                }
                            }
                        }
                        else
                        {

                            @TempData["Message"] = "Employee ID Already Exist";

                        }

                    }
                    else
                    {

                        @TempData["Message"] = "Email ID Already Exist";
                    }
             //   }
                //else
                //{

                //    @TempData["Message"] = "User Name Already Exist";

                //}
            }
         //   ViewBag.ExistStatus = 1;
            return RedirectToAction("RegisterUser");

        }

        #endregion

        #region View User Admin/COE
        [HttpGet]
        public ActionResult ViewUser(int EmpId = 0, int RoleId = 0, string UserFirstName = "", string UserLastName = "", string UserEmailId = "", string UsePhone = "")
        {
            @TempData["Name"] = Session["Name"];
            UserDetailsViewModel userDetailsVM = new UserDetailsViewModel();
            userDetailsVM.Roles = userRepository.GetRoles().Where(x => x.RoleId != 4).ToList();
            //get All info od users
            if (EmpId == 0 && RoleId == 0 && string.IsNullOrEmpty(UserFirstName) && string.IsNullOrEmpty(UserEmailId) && string.IsNullOrEmpty(UsePhone))
            {

                userDetailsVM.GetViewUsers = userRepository.GetAllUser().ToList();

            }

            //get All info for particular search
            if (RoleId != 0 || EmpId != 0 || !string.IsNullOrEmpty(UserFirstName) || !string.IsNullOrEmpty(UserLastName) || !string.IsNullOrEmpty(UserEmailId) || !string.IsNullOrEmpty(UsePhone))
            {
                userDetailsVM.RoleId = RoleId;

                userDetailsVM.GetViewUsers = userRepository.SearchUser(RoleId, EmpId, UserFirstName, UserLastName, UserEmailId, UsePhone).ToList();
            }



            return View(userDetailsVM);
        }
        [HttpPost]
        public ActionResult ViewUser(UserDetailsViewModel userDetailsVM)
        {
            int? empId = 0;
            int userRollId = 0;
            string Userfirstname = "";
            string useremailid = "";
            string userphone = "";
            string Userlastname = "";

            if (userDetailsVM.EmployeeId != 0 || userDetailsVM.RoleId != 0)
            {
                empId = userDetailsVM.EmployeeId;
                userRollId = userDetailsVM.RoleId;

            }
            if (!string.IsNullOrEmpty(userDetailsVM.FirstName))
            {
                Userfirstname = userDetailsVM.FirstName;

            }
            if (!string.IsNullOrEmpty(userDetailsVM.LastName))
            {
                Userlastname = userDetailsVM.LastName;

            }
            if (!string.IsNullOrEmpty(userDetailsVM.EmailID))
            {
                useremailid = userDetailsVM.EmailID;

            }
            if (!string.IsNullOrEmpty(userDetailsVM.UserPhone))
            {
                userphone = userDetailsVM.UserPhone;
            }
            return RedirectToAction("ViewUser", new { EmpId = empId, RoleId = userRollId, UserFirstName = Userfirstname, UserLastName = Userlastname, UserEmailId = useremailid, UsePhone = userphone });


        }

        #endregion

        #region View Doctor
        [HttpGet]

MCMD.Web/Controllers/Doctor/DocMediaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MCMD.ViewModel.Administration;
using MCMD.IRepository.AdminInterfaces;
using MCMD.EntityRepository.AdminRepository;
using MCMD.EntityModel;
using MCMD.EntityModel.Administration;



namespace MCMD.Web.Controllers.Doctor
{
    public class DocMediaController : Controller
    {
        public ApplicationDbContext db = new ApplicationDbContext();

        private IMediaRepository MediaRepository;
        public DocMediaController(IMediaRepository _MediaRepository)
        {
            this.MediaRepository = _MediaRepository;
        }
        // GET: DocMedia
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            @TempData["Name"] = Session["Name"];
            //Session["Doctor"] = 3;
            int Id = (Convert.ToInt32(Session["Doctor"]));
            MediaViewModel _MediaVM = new MediaViewModel();
            _MediaVM.GetMedialist = MediaRepository.GetMedias().Where(x => x.InactiveFlag == "N" && x.LoginId == Id).ToList();
            return View(_MediaVM);
        }
        [HttpPost]
        public ActionResult Create(Media media, MediaViewModel mediaVM, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {
                int Id = (Convert.ToInt32(Session["Doctor"]));
                if (file != null)
                {

                    Session["Media"] = Id;
                    int MediaSession = Convert.ToInt32(Session["Media"]);
                    mediaVM.LoginId = MediaSession;
                    MediaRepository.InsertMedia(media, mediaVM, file);
                    MediaRepository.Save();

                    @TempData["SuccessMessage"] = mediaVM.Message;

                    Session["Media"] = null;
                    return RedirectToAction("Create");
                }
            }
            return View(mediaVM);

        }

        #region Delete Media
        [HttpPost]
        public ActionResult BatchDelete(int[] deleteInputs)
        {

            if (deleteInputs != null)
            {
                foreach (var item in deleteInputs)
                {

                    Media medias = db.medias.Find(item);
                    if (User == null)
                    {
                        // return HttpNotFound();
                    }
                    else
                    {
                        medias.InactiveFlag = "Y";
                        medias.ModifiedDate = DateTime.Now;

                        MediaRepository.UpdateMedia(medias);
                        MediaRepository.Save();
                        @TempData["AddNewItemMessage"] = "User having Media is deleted successfully";

                    }



                }

            }
            return Json("Media", JsonRequestBehavior.AllowGet);
        }

        #endregion

    }
}

MCMD.Web/Views/DocMedia/Create.cshtml
@model MCMD.ViewModel.Administration.MediaViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_DoctorLayout.cshtml";
}

@{

    int Pages = 10;
    WebGrid grid = new WebGrid(Model.GetMedialist, canPage: true, rowsPerPage: Pages);
    grid.Pager(WebGridPagerModes.NextPrevious);
}

<script type="text/javascript">

    //Delete User on click
    function DeleteUserData(varid) {
        if (varid != null) {
            if (confirm('Are you sure want to delete the selected user')) {
                var deleteInputs = [];
                //$('.chkview:checked').each(function (i, chk) {
                deleteInputs.push(varid);
                //});
                var url = '@Url.Action("BatchDelete", "DocMedia")';
                $.ajax({
                    type: "POST",
                    async: false,
                    cache: false,
                    url: url,
                    traditional: true,
                    data: { deleteInputs: deleteInputs },
                    success: function (data) {
                        var url = '@Url.Action("Create", "DocMedia")';
                        window.location.href = url;

                    }
                });
            }
        }
    }

</script>

<!-- BEGIN PAGE CONTAINER-->
<div class="container-fluid">
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
        <div class="span12">

            <h3 class="page-title"></h3>
            <ul class="breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="">Home</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li>
                    <a href="#">My Profile</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li>
                    <a href="#">Media</a>
                    <span class="icon-angle-right"></span>
                </li>
            </ul>
        </div>

    </div>
    <div class="well">
        <span class="label label-important">NOTE!</span>
        <span>
            <span class="bold">Video Uploading Size is 1GB </span>

        </span>
    </div>
    <div>
        <span class="text-success">@TempData["SuccessMessage"]</span>
        <span class="text-success">@TempData["AddNewItemMessage"]</span>
        <span class="text-error">@TempData["Message"]</span>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="portlet box blue ">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i> Upload Photo and Video</div>

        </div>

        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            @using (Html.BeginForm(Html.BeginForm("Create", "DocMedia",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "form-horizontal form-bordered", enctype = "multipart/form-data" })))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="control-group">
                    <label class="control-label">Clinic Name<span class="required">*</span></label>
                    <div class="controls">

                        <input id="ImagePath" title="Upload a product image"
                               type="file" name="file" />

                    </div>
                </div>

                <div class="form-actions">

                    <button type="Submit" id="btnCreate" class="btn blue" name="btnCreate">Submit</button>

                    <button type="button" id="btnscd" class="btn" name="btnscd" onclick="location.href='@Url.Action("Create", "DocMedia")'">Reset</button>
                </div>
            }

            <!-- END FORM-->
        </div>


    </div>
    <div class="portlet">

        <div class="portlet-body">
            @grid.GetHtml(
                                                   tableStyle: "table table-striped table-bordered table-advance table-hover",
                                         footerStyle: "gridFooter",
                                                alternatingRowStyle: "alt",
                                                 htmlAttributes: new { id = "grdUsers" },
                                                 mode: WebGridPagerModes.All,
                                                 firstText: "<< First",
                            previousText: "< Previous", nextText: "Next >",
                            lastText: "Last >>",
                                             columns: new[] {


                                              grid.Column("FolderFilePath", header: "Image",

                 format: (item) =>
                 {
                     return Html.Raw(string.Format("<text><img src=\"{0}\" alt=\"Image\" width='100px' height='100px'/></text>", Url.Content(@item.FolderFilePath)));
                 }
                ),

                                                                                     grid.Column(header: "Option", format: @<text>


                    <a id="btnDelete" style="cursor:pointer;" onclick="DeleteUserData( @item.MediaId)">Delete</a>
                                                                                    </text>)
                                        })

        </div>

    </div>

    <!-- END PAGE CONTENT-->
</div>
<!-- END PAGE CONTAINER-->
@*@using (Html.BeginForm("Create", "Media", null, FormMethod.Post,
                                  new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()


        <div class="container">
            <div class="login-container">
                <div class="form-container">

                    <h2>Image and Video uploading</h2>
                    <hr />
                    <div style="font-size:large;color:#1f317f">
                        @TempData["UserName"]
                    </div>

                    <h5 class="text-success">[ Note - Video Uploading Size is 1GB ]</h5>
                    <div class="form-horizontal">
                        <div class="validation-summary">@Html.ValidationSummary(true)</div>
                        <div class="form-group">

                            <div class="col-sm-6 input-group">

                                <input id="ImagePath" title="Upload a product image"
                                       type="file" name="file" />
                            </div>
                        </div>




                        <span class="fancybox-error" style="color:red;">

                            @TempData["Message"]

                        </span>
                        <div class="form-group">

                            <div class="col-md-offset-2 col-md-10">
                                <button type="button" id="btnscd" name="btnscd" onclick="location.href='@Url.Action("ViewDoctor", "User")'">Back</button>
                                <button type="Submit" id="btnSave" name="btnRegister">Submit</button>
                                <button type="button" id="btnscd" name="btnscd" onclick="location.href='@Url.Action("Create", "UpgradeService")'">Next</button>

                            </div>
                        </div>

                    </div>
                </div>


            </div>
            <div class="form">
                <div class="col-sm-12">
                    <div class="data-table">

                        @grid.GetHtml(
                                               tableStyle: "footable",
                                             footerStyle: "gridFooter",
                                                    alternatingRowStyle: "alt",
                                                     htmlAttributes: new { id = "grdUsers" },
                                                     mode: WebGridPagerModes.All,
                                                   firstText: "<< First",
                                previousText: "< Previous", nextText: "Next >",
                                lastText: "Last >>",
                                                 columns: new[] {
                                                // grid.Column("MediaId",header: "Media Id", canSort: false),
                                              //   grid.Column("LoginId",header: "Login Id", canSort: false),
                                               //  grid.Column("FolderFilePath",header: "Folder File Path", canSort: false),

                                                  grid.Column("FolderFilePath", header: "Image",

                     format: (item) =>
                     {
                         return Html.Raw(string.Format("<text><img src=\"{0}\" alt=\"Image\" width='100px' height='100px'/></text>", Url.Content(@item.FolderFilePath)));
                     }
                    ),

                                                                                         grid.Column(header: "Option", format: @<text>


                        <a id="btnDelete" style="cursor:pointer;" onclick="DeleteUserData( @item.MediaId)">Delete</a>
                                                                                        </text>)
                                            })



                    </div>
                </div>
            </div>
        </div>




    }*@


@Scripts.Render("~/bundles/jqueryval")