MCMD.Web/Controllers/Doctor/DocClinicInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MCMD.EntityModel;
using MCMD.EntityModel.Doctor;
using MCMD.IRepository.AdminInterfaces;
using MCMD.ViewModel.Administration;
using MCMD.EntityModel.Administration;
namespace MCMD.Web.Controllers.Doctor
{
    public class DocClinicInfoController : Controller
    {

        public ApplicationDbContext db = new ApplicationDbContext();
        private IDoctorClinicInformation doctorClinicRepository;

        public DocClinicInfoController(IDoctorClinicInformation _doctorClinicRepository)
        {
            this.doctorClinicRepository = _doctorClinicRepository;
        }
        // GET: DocClinicInfo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            @TempData["Name"] = Session["Name"];
            int Id = (Convert.ToInt32(Session["Doctor"]));

            Session["EditDoctor"] = Id;
            //Create object of View Model Class
            DoctorClinicInformationViewModel doctorClinicVM = new DoctorClinicInformationViewModel();

            //Convert the into  the List
            //Convert the into  the List
            doctorClinicVM.countyList = doctorClinicRepository.GetCountrys().ToList();
            doctorClinicVM.stateList = doctorClinicRepository.GetStates().ToList();
            doctorClinicVM.cityList = doctorClinicRepository.GetCities().ToList();
            doctorClinicVM.UserLogins = doctorClinicRepository.GetUsers().ToList();

            if (Id != 0)
            {

                List<DoctorClinicInformation> NewClinic = doctorClinicRepository.GetClinic().Where(x => x.LoginId == Id).ToList();
                foreach (var item in NewClinic)
                {

                    doctorClinicVM.ClinicName = item.ClinicName;
                    doctorClinicVM.ClinicAddress = item.ClinicAddress;
                    doctorClinicVM.ClinicPhoneNo = item.ClinicPhoneNo;
                    doctorClinicVM.ClinicFees = item.ClinicFees;
                    doctorClinicVM.Country = item.Country;
                    doctorClinicVM.State = item.State;
                    doctorClinicVM.City = item.City;
                    doctorClinicVM.ClinicServices = item.ClinicServices;
                    doctorClinicVM.AwardsAndRecognization = item.AwardsAndRecognization;
                    doctorClinicVM.AboutClinic = item.AboutClinic;
                    doctorClinicVM.ZipCode = item.ZipCode;
                }



            }
            return View(doctorClinicVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(DoctorClinicInformationViewModel _doctorClinicVM)
        {
            try
            {
                //  ModelState.Clear();  // Cleare Model state
                if (ModelState.IsValid)
                {
                    _doctorClinicVM.LoginId = Convert.ToInt32(Session["Doctor"]);
                    var existingUser = db.DoctorsClinicInfos.FirstOrDefault(u => u.LoginId == _doctorClinicVM.LoginId);

                    int Id = (Convert.ToInt32(Session["Doctor"]));


                    if (ReferenceEquals(existingUser, null))
                    {
                        var newClinic = new DoctorClinicInformation();
                        newClinic.ClinicName = _doctorClinicVM.ClinicName;
                        newClinic.ClinicAddress = _doctorClinicVM.ClinicAddress;
                        newClinic.ClinicPhoneNo = _doctorClinicVM.ClinicPhoneNo;
                        newClinic.ClinicFees = _doctorClinicVM.ClinicFees;
                        newClinic.Country = _doctorClinicVM.Country;
                        newClinic.State = _doctorClinicVM.State;
                        newClinic.City = _doctorClinicVM.City;
                        newClinic.ZipCode = _doctorClinicVM.ZipCode;
                        newClinic.ClinicServices = _doctorClinicVM.ClinicServices;
                        newClinic.AwardsAndRecognization = _doctorClinicVM.AwardsAndRecognization;
                        newClinic.AboutClinic = _doctorClinicVM.AboutClinic;
                        newClinic.InactiveFlag = "N";
                        newClinic.CreatedByID = 1;// for now we add 1 later we change
                        newClinic.CreatedDate = DateTime.Now;
                        newClinic.ModifiedByID = 1;// for now we add 1 later we change
                        newClinic.ModifiedDate = DateTime.Now;
                        newClinic.LoginId = Id;

                        doctorClinicRepository.InsertClinic(newClinic);
                        doctorClinicRepository.Save();
                        @TempData["SuccessMessage"] = "Succsessfully save data";
                    }
                    else
                    {

                        existingUser.ClinicName = _doctorClinicVM.ClinicName;
                        existingUser.ClinicAddress = _doctorClinicVM.ClinicAddress;
                        existingUser.ClinicPhoneNo = _doctorClinicVM.ClinicPhoneNo;
                        existingUser.ClinicFees = _doctorClinicVM.ClinicFees;
                        existingUser.Country = _doctorClinicVM.Country;
                        existingUser.State = _doctorClinicVM.State;
                        existingUser.City = _doctorClinicVM.City;
                        existingUser.ZipCode = _doctorClinicVM.ZipCode;
                        existingUser.ClinicServices = _doctorClinicVM.ClinicServices;
                        existingUser.AwardsAndRecognization = _doctorClinicVM.AwardsAndRecognization;
                        existingUser.AboutClinic = _doctorClinicVM.AboutClinic;
                        existingUser.InactiveFlag = "N";
                        existingUser.CreatedByID = 1;// for now we add 1 later we change
                        existingUser.CreatedDate = DateTime.Now;
                        existingUser.ModifiedByID = 1;// for now we add 1 later we change
                        existingUser.ModifiedDate = DateTime.Now;
                        existingUser.LoginId = Id;

                        //Update if already exit 
                        doctorClinicRepository.UpdateClinic(existingUser);
                        doctorClinicRepository.Save();
                        @TempData["SuccessMessage"] = "Succsessfully Update data";

                    }

                }


            }
            catch (Exception)
            {
                //ModelState.AddModelError(string.Empty, "Unable to save changes. Try again, and if the problem persists contact your system administrator.");
                @TempData["Message"] = "Unable to save changes. Try again, and if the problem persists contact your system administrator.";
            }
            return RedirectToAction("Create");
        }
    }
}

MCMD.Web/Views/DocClinicInfo/Create.cshtml
@model MCMD.ViewModel.Administration.DoctorClinicInformationViewModel
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_DoctorLayout.cshtml";
}

<script src="@Url.Content("~/Scripts/jquery-1.7.1.min.js")" type="text/javascript"></script>




<!-- BEGIN PAGE CONTAINER-->
<div class="container-fluid">
    <!-- BEGIN PAGE HEADER-->
    <div class="row-fluid">
        <div class="span12">

            <h3 class="page-title"></h3>
            <ul class="breadcrumb">
                <li>
                    <i class="icon-home"></i>
                    <a href="">Home</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li>
                    <a href="#">My Profile</a>
                    <span class="icon-angle-right"></span>
                </li>
                <li>
                    <a href="#">Clinic Information</a>
                    <span class="icon-angle-right"></span>
                </li>
            </ul>
        </div>
        <div>
            <span class="text-success">@TempData["SuccessMessage"]</span>
            <span class="text-error">@TempData["Message"]</span>
        </div>
    </div>
    <!-- END PAGE HEADER-->
    <!-- BEGIN PAGE CONTENT-->
    <div class="portlet box blue ">
        <div class="portlet-title">
            <div class="caption"><i class="icon-reorder"></i> My Clinic Information</div>

        </div>

        <div class="portlet-body form">
            <!-- BEGIN FORM-->
            @using (Html.BeginForm(Html.BeginForm("Create", "DocClinicInfo",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "form-horizontal form-bordered" })))
            {
                @Html.AntiForgeryToken()
                @Html.ValidationSummary(true)
                <div class="control-group">
                    <label class="control-label">Name of the Clinic<span class="required">*</span></label>
                    <div class="controls">

                        @Html.TextBoxFor(u => u.ClinicName, new { @class = "m-wrap span12", @placeholder = " Clinic Name", @maxlength = "30", @autocomplete = "off" })
                        @Html.ValidationMessageFor(u => u.ClinicName, string.Empty, new { @class = "text-error" })

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Address<span class="required">*</span> </label>
                    <div class="controls">
                        @Html.TextBoxFor(u => u.ClinicAddress, new { @class = "m-wrap span12", @placeholder = "Clinic Address", @maxlength = "30", @autocomplete = "off" })
                        @Html.ValidationMessageFor(u => u.ClinicAddress, string.Empty, new { @class = "text-error" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Phone #<span class="required">*</span></label>
                    <div class="controls">
                        @Html.TextBoxFor(u => u.ClinicPhoneNo, new { @class = "m-wrap span12", @placeholder = "Clinic Phone No", @maxlength = "30", @autocomplete = "off" })
                        @Html.ValidationMessageFor(u => u.ClinicPhoneNo, string.Empty, new { @class = "text-error" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Fees</label>
                    <div class="controls">
                        @Html.TextBoxFor(u => u.ClinicFees, new { @class = "m-wrap span12", @placeholder = "Clinic Fees", @maxlength = "30", @autocomplete = "off" })
                        @Html.ValidationMessageFor(u => u.ClinicFees, string.Empty, new { @class = "text-error" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Country<span class="required">*</span></label>
                    <div class="controls">
                        @Html.DropDownListFor(m => m.CountryId, new SelectList(Model.countyList, "CountryId", "CountryName"),
                             "-Select-", new { @class = "m-wrap span6" })
                        @Html.ValidationMessageFor(m => m.CountryId, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">State<span class="required">*</span> </label>
                    <div class="controls">
                        @Html.DropDownListFor(m => m.StateId, new SelectList(Model.stateList, "StateId", "StateName"),
                          "-Select-", new { @class = "m-wrap span6" })
                        @Html.ValidationMessageFor(m => m.StateId, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">City<span class="required">*</span></label>
                    <div class="controls">
                        @Html.DropDownListFor(m => m.CityId, new SelectList(Model.cityList, "CityId", "CityName"),
                          "-Select-", new { @class = "m-wrap span6" })
                        @Html.ValidationMessageFor(m => m.CityId, "", new { @class = "text-error" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Pin Code<span class="required">*</span></label>
                    <div class="controls">
                        @Html.TextBoxFor(u => u.ZipCode, new { @class = "m-wrap span12", @placeholder = "Zip Code", @maxlength = "30", @autocomplete = "off" })
                        @Html.ValidationMessageFor(u => u.ZipCode, string.Empty, new { @class = "text-error" })
                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Services offered</label>
                    <div class="controls">
                        @Html.TextBoxFor(u => u.ClinicServices, new { @class = "m-wrap span12", @placeholder = "Clinic Services", @maxlength = "30", @autocomplete = "off" })

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">Awards And Recognization</label>
                    <div class="controls">
                        @Html.TextBoxFor(u => u.AwardsAndRecognization, new { @class = "m-wrap span12", @placeholder = "AwardsAnd Recognization", @maxlength = "30", @autocomplete = "off" })

                    </div>
                </div>
                <div class="control-group">
                    <label class="control-label">About Clinic</label>
                    <div class="controls">
                        @Html.TextAreaFor(u => u.AboutClinic, new { @class = "m-wrap span12", @placeholder = "AboutClinic", @maxlength = "30", @autocomplete = "off" })

                    </div>
                </div>

                <div class="form-actions">

                    <button type="Submit" id="btnCreate" class="btn blue" name="btnCreate">Submit</button>

                    <button type="button" id="btnscd" class="btn" name="btnscd" onclick="location.href='@Url.Action("Create", "DocClinicInfo")'">Reset</button>
                </div>
            }

            <!-- END FORM-->
        </div>


    </div>

    <!-- END PAGE CONTENT-->
</div>
<!-- END PAGE CONTAINER-->
@Scripts.Render("~/bundles/jqueryval")